import { NextRequest, NextResponse } from 'next/server';
import { createPublicClient, http } from 'viem';
import { sepolia } from 'viem/chains';
import type { ExperienceResult } from '@/lib/agents';
import { keccak256, encodePacked } from 'viem';
import { CONTRACTS, UserPOIRegistryABI, RoamEscrowABI, poiIdFromSlug } from '@/lib/contracts';

// ─── Viem client for server-side on-chain reads ───────────────────────────────

const publicClient = createPublicClient({
  chain:     sepolia,
  transport: http(process.env.NEXT_PUBLIC_RPC_URL || 'https://sepolia.infura.io/v3/'),
});

// ─── Dev fallback mock data ────────────────────────────────────────────────────

const MOCK_EXPERIENCES: Record<string, ExperienceResult> = {
  'cannes-01': {
    story:
      'The Palais des Festivals rises like a monument to cinematic dreams. Each May, the red carpet unfurls here and the world watches stars ascend these iconic steps. But long before the glamour, this stretch of coastline was a quiet fishing village where Prosper Mérimée once stood and declared Cannes too beautiful to remain unknown.',
    venue: {
      name:   'Café Roma',
      isOpen: true,
      note:   'Excellent croque-monsieur, 3 min walk east along La Croisette.',
      suggestedBy: [
        { name: 'alice.eth' },
        { name: 'bob.eth' },
        { name: 'marco.eth' },
        { name: 'sophie.eth' },
      ],
    },
    audioUrl: '',
  },
  default: {
    story:    'A story about this remarkable place is being generated by the agent swarm...',
    venue:    { name: 'Local Café', isOpen: true, note: 'A cozy spot nearby.' },
    audioUrl: '',
  },
};

const ORCHESTRATOR_URL = process.env.ORCHESTRATOR_URL || 'http://localhost:3001';
const IS_DEV = process.env.NODE_ENV === 'development';

// ─── GET /api/experience/[id] ─────────────────────────────────────────────────

export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  const poiId    = params.id;
  const lang     = request.nextUrl.searchParams.get('lang')       || 'en';
  const userId   = request.nextUrl.searchParams.get('userId')     || 'anonymous';
  const stream   = request.nextUrl.searchParams.get('stream')     === 'true';
  const userAddr = request.nextUrl.searchParams.get('userAddress');

  // ── Auth check: verify POI is unlocked OR payment is locked in escrow ───
  if (userAddr && userAddr.startsWith('0x')) {
    try {
      const poiBytes32 = poiIdFromSlug(poiId);
      const addr = userAddr as `0x${string}`;

      const isUnlocked = await publicClient.readContract({
        address:      CONTRACTS.userPOIRegistry,
        abi:          UserPOIRegistryABI,
        functionName: 'unlockedPOIs',
        args:         [addr, poiBytes32],
      });

      if (!isUnlocked) {
        // Also accept if payment is locked in escrow (release not yet called)
        const escrowKey = keccak256(encodePacked(['bytes32', 'address'], [poiBytes32, addr]));
        const payment = await publicClient.readContract({
          address:      CONTRACTS.roamEscrow,
          abi:          RoamEscrowABI,
          functionName: 'payments',
          args:         [escrowKey],
        }) as [string, string, bigint, boolean, boolean];

        const [payer, , , released, refunded] = payment;
        const hasValidPayment = payer !== '0x0000000000000000000000000000000000000000' && !released && !refunded;

        if (!hasValidPayment) {
          return NextResponse.json({ error: 'POI not unlocked' }, { status: 403 });
        }
      }
    } catch (err: unknown) {
      console.warn('[API /experience] Chain read failed, skipping auth check:', err);
    }
  }

  // ── SSE streaming mode ────────────────────────────────────────────────────
  if (stream) {
    const upstreamUrl = `${ORCHESTRATOR_URL}/orchestrate/stream?poiId=${poiId}&lang=${lang}&userId=${userId}${userAddr ? `&userAddress=${userAddr}` : ''}`;
    try {
      const upstream = await fetch(upstreamUrl, { signal: AbortSignal.timeout(180_000) });
      if (!upstream.ok || !upstream.body) throw new Error(`Upstream ${upstream.status}`);
      return new NextResponse(upstream.body, {
        headers: {
          'Content-Type':                'text/event-stream',
          'Cache-Control':               'no-cache',
          'Connection':                  'keep-alive',
          'Access-Control-Allow-Origin': '*',
        },
      });
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      // In dev, fall back to a single mock SSE event
      if (IS_DEV) {
        const mock = MOCK_EXPERIENCES[poiId] ?? MOCK_EXPERIENCES.default;
        const encoder = new TextEncoder();
        const body    = encoder.encode(`data: ${JSON.stringify({ type: 'result', ...mock })}\n\ndata: [DONE]\n\n`);
        return new NextResponse(body, {
          headers: { 'Content-Type': 'text/event-stream', 'Cache-Control': 'no-cache' },
        });
      }
      return NextResponse.json({ error: message }, { status: 500 });
    }
  }

  // ── JSON mode: POST /orchestrate ──────────────────────────────────────────
  try {
    const res = await fetch(`${ORCHESTRATOR_URL}/orchestrate`, {
      method:  'POST',
      headers: { 'Content-Type': 'application/json' },
      body:    JSON.stringify({ poiId, userId, lang, userAddress: userAddr ?? '' }),
      signal:  AbortSignal.timeout(180_000),
    });

    if (!res.ok) {
      const errText = await res.text();
      throw new Error(`Orchestrator ${res.status}: ${errText}`);
    }

    const data = await res.json();
    return NextResponse.json(data);
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    console.error('[API /experience] Orchestrator error:', message);

    // In dev, fall back to mock instead of erroring
    if (IS_DEV) {
      const mock = MOCK_EXPERIENCES[poiId] ?? MOCK_EXPERIENCES.default;
      return NextResponse.json({ ...mock, _mock: true });
    }

    return NextResponse.json({ error: message }, { status: 502 });
  }
}
