import { NextRequest, NextResponse } from 'next/server';
import type { ExperienceResult } from '@/lib/agents';

// Mock data for development — replace with real orchestrator call
const MOCK_EXPERIENCES: Record<string, ExperienceResult> = {
  'cannes-01': {
    story:
      'The Palais des Festivals rises like a monument to cinematic dreams. Each May, the red carpet unfurls here and the world watches stars ascend these iconic steps. But long before the glamour, this stretch of coastline was a quiet fishing village where Prosper Mérimée once stood and declared Cannes too beautiful to remain unknown.',
    venue: {
      name: 'Café Roma',
      isOpen: true,
      note: 'Excellent croque-monsieur, 3 min walk east along La Croisette.',
      suggestedBy: [
        { name: 'alice.eth' },
        { name: 'bob.eth' },
        { name: 'marco.eth' },
        { name: 'sophie.eth' },
      ],
    },
    audioUrl: '',
  },
  default: {
    story: 'A story about this remarkable place is being generated by the agent swarm...',
    venue: {
      name: 'Local Café',
      isOpen: true,
      note: 'A cozy spot nearby.',
    },
    audioUrl: '',
  },
};

const ORCHESTRATOR_URL = process.env.ORCHESTRATOR_URL || 'http://localhost:3001';

// GET /api/experience/[id] — proxies to orchestrator
// Add ?stream=true for SSE streaming (step-by-step progress)
export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  const poiId = params.id;
  const lang = request.nextUrl.searchParams.get('lang') || 'en';
  const userId = request.nextUrl.searchParams.get('userId') || 'anonymous';
  const stream = request.nextUrl.searchParams.get('stream') === 'true';

  // SSE streaming mode — proxy SSE from orchestrator to client
  if (stream) {
    const upstreamUrl = `${ORCHESTRATOR_URL}/orchestrate/stream?poiId=${poiId}&lang=${lang}&userId=${userId}`;

    try {
      const upstream = await fetch(upstreamUrl, {
        signal: AbortSignal.timeout(180000),
      });

      if (!upstream.ok || !upstream.body) {
        return NextResponse.json({ error: 'Orchestrator stream unavailable' }, { status: 502 });
      }

      return new NextResponse(upstream.body, {
        headers: {
          'Content-Type': 'text/event-stream',
          'Cache-Control': 'no-cache',
          'Connection': 'keep-alive',
          'Access-Control-Allow-Origin': '*',
        },
      });
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      return NextResponse.json({ error: message }, { status: 500 });
    }
  }

  // Default: JSON response via POST /orchestrate
  try {
    const res = await fetch(`${ORCHESTRATOR_URL}/orchestrate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ poiId, userId, lang }),
      signal: AbortSignal.timeout(180000),
    });

    if (!res.ok) {
      const err = await res.text();
      return NextResponse.json(
        { error: `Orchestrator error: ${res.status} — ${err}` },
        { status: 502 }
      );
    }

    const data = await res.json();
    return NextResponse.json(data);
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    console.error('[API /experience] Error:', message);
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
