import { NextRequest, NextResponse } from 'next/server';
import type { ExperienceResult } from '@/lib/agents';

// Mock data for development — replace with real orchestrator call
const MOCK_EXPERIENCES: Record<string, ExperienceResult> = {
  'cannes-01': {
    story:
      'The Palais des Festivals rises like a monument to cinematic dreams. Each May, the red carpet unfurls here and the world watches stars ascend these iconic steps. But long before the glamour, this stretch of coastline was a quiet fishing village where Prosper Mérimée once stood and declared Cannes too beautiful to remain unknown.',
    venue: {
      name: 'Café Roma',
      isOpen: true,
      note: 'Excellent croque-monsieur, 3 min walk east along La Croisette.',
    },
    audioUrl: '',
  },
  default: {
    story: 'A story about this remarkable place is being generated by the agent swarm...',
    venue: {
      name: 'Local Café',
      isOpen: true,
      note: 'A cozy spot nearby.',
    },
    audioUrl: '',
  },
};

export async function GET(
  _request: NextRequest,
  { params }: { params: { id: string } }
) {
  const poiId = params.id;

  // TODO: call orchestrator agent at agents/orchestrator with { poiId, lang }
  // The orchestrator fans out to history-agent, food-agent, voice-agent
  // and returns the merged ExperienceResult

  const experience = MOCK_EXPERIENCES[poiId] || MOCK_EXPERIENCES['default'];

  return NextResponse.json(experience);
}
